version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://redis:6379
      # AEM Deployment Configuration
      - AEM_AUTHOR_URL=${AEM_AUTHOR_URL:-http://host.docker.internal:4502}
      - AEM_USERNAME=${AEM_USERNAME:-admin}
      - AEM_PASSWORD=${AEM_PASSWORD:-admin}
      - MAVEN_PROFILES=${MAVEN_PROFILES:-adobe-public,autoInstallPackage}
      - SKIP_TESTS=${SKIP_TESTS:-true}
    depends_on:
      - redis
    volumes:
      - ./uploads:/tmp/aem_uploads
      - ./project_code:/app/project_code  # Mount project code for AEM deployment
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  redis_data:
  uploads:
